### ISSUE TITLE
Tcl echo command not working

### ISSUE THREAD

**Issue by dukus** [dukus/digiCamControl#266]
http://digicamcontrol.com/phpbb/viewtopic.php?f=3&t=1697&p=4980#p4980

**Comment by merchant23** [comment]
Have you tried using (puts) instead of (echo) to print out debug messages?  According to this [link](http://wiki.tcl.tk/1969), the (echo) command is part of TclX package, which your Tcl version may not contain.

Also, the following line in your code looks incorrect syntax-wise. 

BEFORE:
set now clock seconds

SUGGESTED:
set now [clock seconds]
